name: Database Keepalive

# 设置工作流触发条件：每天凌晨 2 点执行
on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨 2 点执行
  workflow_dispatch:     # 也允许手动触发

jobs:
  database-keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install @supabase/supabase-js dotenv
      
      - name: Create config file
        # 将环境变量写入配置文件，避免 JSON 解析问题
        run: echo '${{ secrets.DB_CONFIG }}' > db-config.json
      
      - name: Run database keepalive script
        run: node database-keepalive-file.js
