name: Database Keepalive

# 触发条件：可以通过定时任务触发
on:
  schedule:
    # 每天执行，可以根据需要调整
    - cron: '0 0 * * *'
  # 也可以手动触发
  workflow_dispatch:

jobs:
  database-keepalive:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install pg dotenv
          
      - name: Execute database queries
        env:
          # 定义数据库连接和查询语句的JSON数组
          DB_CONNECTIONS: ${{ secrets.DB_CONNECTIONS }}
        run: node ./db-keepalive.js
